Repository Holmusk/elm-street, pull requests merged in 2019-02, with the labels that each got.

#16 [#12] Add Travis CI config
  .travis.yml
  stack.yaml
Labels: CI

#15 [#7] Implement generic conversion
  elm-street.cabal
  src/Elm.hs
  src/Elm/Ast.hs
  src/Elm/Generic.hs
Labels: generics

#14 [#3] Implement prettyShowDefinition
  elm-street.cabal
  src/Elm.hs
  src/Elm/Print.hs
Labels: pretty printing

#20 [#17] Strip field name prefixes
  .ghci
  src/Elm/Generic.hs
Labels: generics

#21 [#4] Implement pretty enum functions
  .ghci
  src/Elm/Ast.hs
  src/Elm/Print.hs
Labels: pretty printing

#22 [#18] Support primitive elm types
  src/Elm/Ast.hs
  src/Elm/Generic.hs
  src/Elm/Print.hs
Labels: ast, generics, pretty printing

#28 [#23] Add parens for types where needed
  .ghci
  src/Elm/Print.hs
Labels: pretty printing

#30 [#29] Fix showing of types with type parameters
  src/Elm/Generic.hs
Labels: generics, pretty printing

#31 Implement JSON encoders pretty print
  .ghci
  src/Elm/Print.hs
Labels: pretty printing

#32 [#8] Implement writing of elm code to files
  .ghci
  elm-street.cabal
  src/Elm.hs
  src/Elm/Generate.hs
  src/Elm/Print.hs
Labels: pretty printing

#35 [#34] Better support of newtype encoders
  src/Elm/Ast.hs
  src/Elm/Generic.hs
  src/Elm/Print.hs
  stack-8.4.4.yaml
Labels: ast, enhancement, generics, pretty printing

#37 [#5] Implement decoders pretty printing
  src/Elm/Generate.hs
  src/Elm/Print.hs
Labels: json, pretty printing

#39 [#38] Support decoders for newtypes
  src/Elm/Print.hs
Labels: enhancement, pretty printing

#40 [#27] Support UTCTime data type
  elm-street.cabal
  src/Elm/Ast.hs
  src/Elm/Generate.hs
  src/Elm/Generic.hs
  src/Elm/Print.hs
Labels: ast, enhancement, json

#41 Implement executable to generate elm definitions
  elm-street.cabal
  generate-elm/Main.hs
  src/Elm/Generate.hs
Labels: tests

#42 [#33] Create minimal elm project
  README.md
  elm-example/.gitignore
  elm-example/elm.json
  elm-example/public/index.html
  elm-example/public/manifest.json
  elm-example/src/Core/Decoder.elm
  elm-example/src/Core/ElmStreet.elm
  elm-example/src/Core/Encoder.elm
  elm-example/src/Core/Types.elm
  elm-example/src/Main.elm
  elm-example/src/index.js
  elm-example/src/main.css
  elm-example/src/registerServiceWorker.js
  elm-example/tests/Tests.elm
  generate-elm/Main.hs
  src/Elm/Generate.hs
  src/Elm/Print.hs
Labels: elm, tests

#46 [#43] create internal library for types
  elm-street.cabal
  generate-elm/Main.hs
  types/Types.hs
Labels: backend, enhancement

#49 Add compile time errors for Generic deriving
  src/Elm/Generic.hs
Labels: generics

#50 Drop support for phantom type variables
  elm-example/src/Core/Decoder.elm
  elm-example/src/Core/Encoder.elm
  elm-example/src/Core/Types.elm
  src/Elm/Generic.hs
  types/Types.hs
Labels: ast, elm, generics, tests

#54 [#44] Create run-backend, patch frontend
  README.md
  backend/Api.hs
  backend/Main.hs
  elm-example/src/Main.elm
  elm-street.cabal
  frontend/.gitignore
  frontend/elm.json
  frontend/elmapp.config.js
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/Api.elm
  frontend/src/Core/Decoder.elm
  frontend/src/Core/ElmStreet.elm
  frontend/src/Core/Encoder.elm
  frontend/src/Core/Types.elm
  frontend/src/Main.elm
  frontend/src/index.js
  frontend/src/main.css
  frontend/src/registerServiceWorker.js
  frontend/tests/Tests.elm
  generate-elm/Main.hs
  src/Elm/Print.hs
  stack.yaml
  types/Types.hs
Labels: backend, elm, enhancement, json

#52 [#51] Write README docs
  README.md
Labels: docs

#56 [#53] Add custom Aeson options and helper functions
  elm-street.cabal
  src/Elm.hs
  src/Elm/Aeson.hs
  src/Elm/Generic.hs
  stack.yaml
  types/Types.hs
Labels: enhancement

#57 [#47] Custom error for constructors with >8 unnamed fields
  src/Elm/Aeson.hs
  src/Elm/Generic.hs
Labels: error-handling, generics

#58 Add docs about DerivingVia and aeson options
  README.md
Labels: docs

#59 [#48] Custom error for Sum typs with named fields
  src/Elm/Aeson.hs
  src/Elm/Generic.hs
Labels: error-handling, generics

#60 Improve Haddock documentation
  elm-street.cabal
  src/Elm/Aeson.hs
  src/Elm/Ast.hs
  src/Elm/Generate.hs
  src/Elm/Generic.hs
  src/Elm/Print.hs
Labels: docs
