Repository Holmusk/elm-street, pull requests merged in 2019-09, with the labels that each got.

#75 [#72] Fix Haskell JSON encoder for unary constructors
  .gitignore
  CHANGELOG.md
  elm-street.cabal
  src/Elm/Aeson.hs
Labels: json

#77 [#74] Generated decoders for unit type does not compile
  CHANGELOG.md
  frontend/src/Core/Decoder.elm
  frontend/src/Core/Encoder.elm
  frontend/src/Core/Types.elm
  src/Elm/Print.hs
  types/Types.hs
Labels: json

#78 [#76] Modernise project
  .travis.yml
  CHANGELOG.md
  Setup.hs
  backend/Main.hs
  elm-street.cabal
  stack-8.4.4.yaml
  stack.yaml
Labels: refactoring

#81 [#80] Fix 'key "tag" not present' issue
  CHANGELOG.md
  frontend/src/Core/Encoder.elm
  src/Elm/Print.hs
Labels: json, pretty printing

#82 [#73] Adding documentation for reserved words in elm
  CHANGELOG.md
  README.md
Labels: docs

#83 [#71] Remove Elm instance for `String` data type
  CHANGELOG.md
  elm-street.cabal
  src/Elm/Generic.hs
Labels: enhancement, generics

#87 [#6] Test Elm build on CI
  .travis.yml
Labels: CI, elm

#88 [#79] Implement pure Elm tests
  .travis.yml
  frontend/tests/Tests.elm
  test/golden/oneType.json
Labels: elm, tests

#85 [#70] Use qualified imports for Types module
  CHANGELOG.md
  frontend/src/Core/Decoder.elm
  frontend/src/Core/Encoder.elm
  frontend/src/Core/Types.elm
  frontend/tests/Tests.elm
  src/Elm/Generate.hs
  src/Elm/Print.hs
  types/Types.hs
Labels: enhancement, pretty printing

#91 Add Elm golden test Json -> OneType
  elm-street.cabal
  frontend/elm.json
  frontend/tests/Tests.elm
  frontend/tests/Tests/Golden.elm
  generate-elm/Main.hs
  test/golden/oneType.json
Labels: elm, tests

#93 [#86] Split Print module
  elm-street.cabal
  src/Elm/Print.hs
  src/Elm/Print/Common.hs
  src/Elm/Print/Decoder.hs
  src/Elm/Print/Encoder.hs
  src/Elm/Print/Types.hs
Labels: refactoring

#94 [#79] Implement golden tests
  elm-street.cabal
  stack-8.4.4.yaml
  test/Spec.hs
  test/Test/Golden.hs
Labels: tests

#84 [#90] Support converting three-tuples
  CHANGELOG.md
  frontend/src/Core/Decoder.elm
  frontend/src/Core/ElmStreet.elm
  frontend/src/Core/Encoder.elm
  frontend/src/Core/Types.elm
  frontend/tests/Tests.elm
  frontend/tests/Tests/Golden.elm
  src/Elm/Ast.hs
  src/Elm/Generate.hs
  src/Elm/Generic.hs
  src/Elm/Print/Decoder.hs
  src/Elm/Print/Encoder.hs
  src/Elm/Print/Types.hs
  test/golden/oneType.json
  types/Types.hs
Labels: ast, elm, enhancement, pretty printing

#97 [#96] Fix newtype bug
  CHANGELOG.md
  README.md
  elm-street.cabal
  frontend/src/Core/Decoder.elm
  frontend/src/Core/Encoder.elm
  frontend/src/Core/Types.elm
  frontend/tests/Tests.elm
  frontend/tests/Tests/Golden.elm
  src/Elm/Print/Common.hs
  src/Elm/Print/Decoder.hs
  src/Elm/Print/Encoder.hs
  src/Elm/Print/Types.hs
  test/golden/oneType.json
  types/Types.hs
Labels: bug, pretty printing
