Repository Holmusk/elm-street, pull requests merged in 2019-03, with the labels that each got.

#62 [#61] Support 8.4.4 for Stack
  .travis.yml
  elm-street.cabal
  src/Elm/Aeson.hs
  stack-8.4.4.yaml
Labels: enhancement

#65 [#64] Fix enum list indentation
  src/Elm/Print.hs
Labels: bug, pretty printing

#68 [#66] Patch generated JSON encoders and decoders
  CHANGELOG.md
  README.md
  elm-street.cabal
  frontend/src/Core/Decoder.elm
  frontend/src/Core/Encoder.elm
  frontend/src/Core/Types.elm
  src/Elm/Print.hs
  types/Types.hs
Labels: elm, json, pretty printing
